export const Images = {
  proPic: require('../Assets/Images/proPic.png'),
  location: require('../Assets/Images/location.png'),
  menu: require('../Assets/Images/menu.png'),
  locationYellow: require('../Assets/Images/locationYellow.png'),
  search: require('../Assets/Images/search.png'),
  star: require('../Assets/Images/star.png'),
  bell: require('../Assets/Images/bell.png'),
  calendar: require('../Assets/Images/calendar.png'),
  person: require('../Assets/Images/person.png'),
  back: require('../Assets/Images/back.png'),
  currentLocation: require('../Assets/Images/currentLocation.png'),
  navigation: require('../Assets/Images/navigation.png'),
  minus: require('../Assets/Images/minus.png'),
  plus: require('../Assets/Images/plus.png'),
  food: require('../Assets/Images/food.png'),
  pool: require('../Assets/Images/pool.png'),
  spa: require('../Assets/Images/spa.png'),
  gym: require('../Assets/Images/gym.png'),
  wifi: require('../Assets/Images/wifi.png'),
  room: require('../Assets/Images/room.png'),
};
