import {Images} from './Images';

export const StaticData = [
  {
    hotelId: 'hotelId1',
    name: 'Ocean View Resort',
    location: 'Mumbai, India',
    address: '123 Ocean Drive, Mumbai',
    rating: 9.1,
    price_per_night: '2500',
    amenities: ['Pool', 'Food', 'Spa', 'Wifi'],
    rooms: [
      {
        room_id: 'OVR001',
        room_type: 'Sea View Room',
        number_of_rooms: 20,
        available_rooms: 20,
        price_per_night: '2500',
        bookedDates: [],
      },
      {
        room_id: 'OVR002',
        room_type: 'Luxury Suite',
        number_of_rooms: 10,
        available_rooms: 10,
        price_per_night: '3500',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId2',
    name: 'City Center Hotel',
    location: 'Ahmedabad, India',
    address: '456 City Center, Ahmedabad',
    rating: 8.5,
    price_per_night: '1500',
    amenities: ['Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'ACH001',
        room_type: 'Standard Room',
        number_of_rooms: 40,
        available_rooms: 40,
        price_per_night: '1500',
        bookedDates: [],
      },
      {
        room_id: 'ACH002',
        room_type: 'Executive Suite',
        number_of_rooms: 15,
        available_rooms: 15,
        price_per_night: '2500',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId3',
    name: 'Tech Park Hotel',
    location: 'Bangalore, India',
    address: '789 Tech Park Road, Bangalore',
    rating: 9.0,
    price_per_night: '1800',
    amenities: ['Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'BTPH001',
        room_type: 'Standard Room',
        number_of_rooms: 50,
        available_rooms: 50,
        price_per_night: '1800',
        bookedDates: [],
      },
      {
        room_id: 'BTPH002',
        room_type: 'Deluxe Suite',
        number_of_rooms: 20,
        available_rooms: 20,
        price_per_night: '2500',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId4',
    name: 'Heritage Hotel',
    location: 'Hyderabad, India',
    address: '101 Heritage Street, Hyderabad',
    rating: 9.2,
    price_per_night: '2200',
    amenities: ['Pool', 'Wifi', 'Spa'],
    rooms: [
      {
        room_id: 'HHH001',
        room_type: 'Classic Room',
        number_of_rooms: 25,
        available_rooms: 25,
        price_per_night: '2200',
        bookedDates: [],
      },
      {
        room_id: 'HHH002',
        room_type: 'Royal Suite',
        number_of_rooms: 10,
        available_rooms: 10,
        price_per_night: '2800',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId5',
    name: 'Urban Oasis',
    location: 'Delhi, India',
    address: '567 Urban Avenue, Delhi',
    rating: 9.5,
    price_per_night: '3000',
    amenities: ['Food', 'Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'DUO001',
        room_type: 'City View Room',
        number_of_rooms: 30,
        available_rooms: 30,
        price_per_night: '3000',
        bookedDates: [],
      },
      {
        room_id: 'DUO002',
        room_type: 'Luxury Suite',
        number_of_rooms: 15,
        available_rooms: 15,
        price_per_night: '3600',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId6',
    name: 'Riverside Resort',
    location: 'Kolkata, India',
    address: '789 Riverside Drive, Kolkata',
    rating: 8.9,
    price_per_night: '2500',
    amenities: ['Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'KRR001',
        room_type: 'Riverside Room',
        number_of_rooms: 20,
        available_rooms: 20,
        price_per_night: '2500',
        bookedDates: [],
      },
      {
        room_id: 'KRR002',
        room_type: 'Garden Suite',
        number_of_rooms: 10,
        available_rooms: 10,
        price_per_night: '3200',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId7',
    name: 'Sunset View Hotel',
    location: 'Mumbai, India',
    address: '456 Sunset Boulevard, Mumbai',
    rating: 8.8,
    price_per_night: '1800',
    amenities: ['Food', 'Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'SVH001',
        room_type: 'City View Room',
        number_of_rooms: 25,
        available_rooms: 25,
        price_per_night: '1800',
        bookedDates: [],
      },
      {
        room_id: 'SVH002',
        room_type: 'Sunset Suite',
        number_of_rooms: 15,
        available_rooms: 15,
        price_per_night: '2400',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId8',
    name: 'Grand Hotel',
    location: 'Ahmedabad, India',
    address: '789 Grand Avenue, Ahmedabad',
    rating: 9.2,
    price_per_night: '3000',
    amenities: ['Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'AGH001',
        room_type: 'Standard Room',
        number_of_rooms: 40,
        available_rooms: 40,
        price_per_night: '3000',
        bookedDates: [],
      },
      {
        room_id: 'AGH002',
        room_type: 'Executive Suite',
        number_of_rooms: 15,
        available_rooms: 15,
        price_per_night: '3600',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId9',
    name: 'Garden Lodge',
    location: 'Bangalore, India',
    address: '101 Garden Lane, Bangalore',
    rating: 8.9,
    price_per_night: '2000',
    amenities: ['Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'GL001',
        room_type: 'Standard Room',
        number_of_rooms: 30,
        available_rooms: 30,
        price_per_night: '2000',
        bookedDates: [],
      },
      {
        room_id: 'GL002',
        room_type: 'Forest Suite',
        number_of_rooms: 10,
        available_rooms: 10,
        price_per_night: '2400',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId10',
    name: 'City View Hotel',
    location: 'Hyderabad, India',
    address: '123 City View Avenue, Hyderabad',
    rating: 8.7,
    price_per_night: '1700',
    amenities: ['Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'HCVH001',
        room_type: 'City View Room',
        number_of_rooms: 25,
        available_rooms: 25,
        price_per_night: '1700',
        bookedDates: [],
      },
      {
        room_id: 'HCVH002',
        room_type: 'Executive Suite',
        number_of_rooms: 15,
        available_rooms: 15,
        price_per_night: '2500',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId11',
    name: 'Luxury Suites',
    location: 'Delhi, India',
    address: '456 Luxury Boulevard, Delhi',
    rating: 9.3,
    price_per_night: '3500',
    amenities: ['Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'DLS001',
        room_type: 'Deluxe Room',
        number_of_rooms: 20,
        available_rooms: 20,
        price_per_night: '3500',
        bookedDates: [],
      },
      {
        room_id: 'DLS002',
        room_type: 'Presidential Suite',
        number_of_rooms: 10,
        available_rooms: 10,
        price_per_night: '4200',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId12',
    name: 'City Center Hotel',
    location: 'Kolkata, India',
    address: '789 City Center Drive, Kolkata',
    rating: 9.1,
    price_per_night: '2800',
    amenities: ['Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'KCCH001',
        room_type: 'Standard Room',
        number_of_rooms: 30,
        available_rooms: 30,
        price_per_night: '2800',
        bookedDates: [],
      },
      {
        room_id: 'KCCH002',
        room_type: 'Suite',
        number_of_rooms: 10,
        available_rooms: 10,
        price_per_night: '3500',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId13',
    name: 'Marina Resort',
    location: 'Mumbai, India',
    address: '101 Marina Drive, Mumbai',
    rating: 9.0,
    price_per_night: '2200',
    amenities: ['Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'MMR001',
        room_type: 'Marina View Room',
        number_of_rooms: 25,
        available_rooms: 25,
        price_per_night: '2200',
        bookedDates: [],
      },
      {
        room_id: 'MMR002',
        room_type: 'Marina Suite',
        number_of_rooms: 15,
        available_rooms: 15,
        price_per_night: '3000',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId14',
    name: 'Skyline Hotel',
    location: 'Delhi, India',
    address: '456 Skyline Avenue, Delhi',
    rating: 8.9,
    price_per_night: '2200',
    amenities: ['Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'DSH001',
        room_type: 'City View Room',
        number_of_rooms: 25,
        available_rooms: 25,
        price_per_night: '2200',
        bookedDates: [],
      },
      {
        room_id: 'DSH002',
        room_type: 'Executive Suite',
        number_of_rooms: 15,
        available_rooms: 15,
        price_per_night: '3000',
        bookedDates: [],
      },
    ],
  },
  {
    hotelId: 'hotelId15',
    name: 'Bayfront Hotel',
    location: 'Kolkata, India',
    address: '789 Bayfront Drive, Kolkata',
    rating: 9.1,
    price_per_night: '2300',
    amenities: ['Gym', 'Pool', 'Wifi'],
    rooms: [
      {
        room_id: 'KBH001',
        room_type: 'Bay View Room',
        number_of_rooms: 20,
        available_rooms: 20,
        price_per_night: '2300',
        bookedDates: [],
      },
      {
        room_id: 'KBH002',
        room_type: 'Executive Suite',
        number_of_rooms: 10,
        price_per_night: '3200',
      },
    ],
  },
];

export const popularCityData = [
  {location: 'Mumbai, India'},
  {location: 'Bangalore, India'},
  {location: 'Ahmedabad, India'},
  {location: 'Hyderabad, India'},
  {location: 'Delhi, India'},
  {location: 'Kolkata, India'},
];

export const HotelDescription = `
Explore a collection of premier hotels across India, each offering a unique blend of luxury and convenience. From the breathtaking Ocean View Resort in Mumbai to the tech-savvy ambiance of the City Center Hotel in Ahmedabad, every stay promises a memorable experience. Indulge in modern comforts at the Tech Park Hotel in Bangalore or immerse yourself in Hyderabad's rich heritage at the elegant Heritage Hotel. Whether it's a rooftop pool with city views at the Urban Oasis in Delhi or serene riverside vistas at the Riverside Resort in Kolkata, each destination caters to discerning travelers seeking comfort and style.

In these hotels, you'll find a perfect balance of relaxation and sophistication. From the grandeur of the Grand Hotel in Ahmedabad to the tranquil ambiance of the Garden Lodge in Bangalore, every establishment offers a retreat tailored to your desires. Whether it's a rejuvenating spa treatment in Luxury Suites, Delhi, or a refreshing dip in the outdoor pool at the Marina Resort, Mumbai, each hotel promises a delightful escape. Experience the charm of the City View Hotel in Hyderabad or savor coastal beauty at the Bayfront Hotel in Kolkata. With impeccable service and top-notch amenities, these hotels redefine hospitality, ensuring a memorable stay for every guest.`;

export const HotelImages = [
  Images.Hotel1,
  Images.Hotel2,
  Images.Hotel3,
  Images.Hotel4,
  Images.Hotel5,
  Images.Hotel6,
  Images.Hotel7,
  Images.Hotel8,
  Images.Hotel9,
  Images.Hotel10,
];
